import { afterAll, beforeEach, describe, expect, test } from "bun:test";
import { createUploadReceipt } from "@api/utils/upload-receipt";
import { createCallerFactory } from "../../trpc/init";
import { storageRouter } from "../../trpc/routers/storage";
import { createTestContext } from "../helpers/test-context";
import { mocks } from "../setup";

const originalProvider = process.env.NEXT_PUBLIC_BACKEND_PROVIDER;
beforeEach(() => {
  process.env.NEXT_PUBLIC_BACKEND_PROVIDER = "local";
});
afterAll(() => {
  if (originalProvider === undefined)
    delete process.env.NEXT_PUBLIC_BACKEND_PROVIDER;
  else process.env.NEXT_PUBLIC_BACKEND_PROVIDER = originalProvider;
});

const createCaller = createCallerFactory(storageRouter);
const txId = "47da6d71-e66a-46e4-92d3-e90b4c3174f8";
const owner = { teamId: "test-team-id", userId: "test-user-id" };
const file = {
  path: [owner.teamId],
  filename: "Receipt.pdf",
  contentType: "application/pdf",
  size: 123,
};
async function completion(
  key = `${owner.teamId}/receipt.pdf`,
  bucket: "vault" | "avatars" | "apps" = "vault",
  userId = owner.userId,
) {
  return {
    bucket,
    files: [
      {
        key,
        receipt: await createUploadReceipt(
          {
            bucket,
            key,
            teamId: owner.teamId,
            size: 123,
            contentType: bucket === "vault" ? "application/pdf" : "image/png",
          },
          userId,
        ),
      },
    ],
  };
}

beforeEach(() => {
  mocks.createSignedUploadUrl.mockReset();
  mocks.createSignedUploadUrl.mockImplementation(() =>
    Promise.resolve({
      url: "http://localhost:9000/upload",
      method: "PUT",
      headers: { "Content-Type": "application/pdf" },
    }),
  );
  mocks.storageHead.mockReset();
  mocks.storageHead.mockImplementation(() =>
    Promise.resolve({
      key: `${owner.teamId}/receipt.pdf`,
      size: 123,
      contentType: "application/pdf",
    }),
  );
  mocks.removeStorage.mockReset();
  mocks.removeStorage.mockImplementation(() => Promise.resolve());
  mocks.upsertDocumentForObject.mockReset();
  mocks.upsertDocumentForObject.mockImplementation(() =>
    Promise.resolve({ id: "document-id" }),
  );
  mocks.getTransactionById.mockReset();
  mocks.getTransactionById.mockImplementation(() => Promise.resolve(null));
  mocks.storagePublicUrl.mockReset();
  mocks.storagePublicUrl.mockImplementation(
    (bucket: string, key: string) => `http://localhost:9000/${bucket}/${key}`,
  );
});

describe("tRPC storage authorization", () => {
  test("issues own vault upload with receipt and canonical key", async () => {
    const result = await createCaller(createTestContext()).createUploadUrls({
      bucket: "vault",
      files: [file],
    });
    expect(result[0]?.key).toBe(`${owner.teamId}/receipt.pdf`);
    expect(result[0]?.receipt).toBeString();
    expect(mocks.createSignedUploadUrl).toHaveBeenCalledWith(
      "vault",
      `${owner.teamId}/receipt.pdf`,
      { contentType: "application/pdf", expiresIn: 600 },
    );
  });
  test("foreign vault/avatars paths and unsupported apps folders cannot presign", async () => {
    for (const [bucket, path] of [
      ["vault", ["foreign-team"]],
      ["avatars", ["foreign-user"]],
      ["apps", ["other"]],
    ] as const) {
      await expect(
        createCaller(createTestContext()).createUploadUrls({
          bucket,
          files: [
            {
              ...file,
              path: [...path],
              contentType: bucket === "vault" ? "application/pdf" : "image/png",
            },
          ],
        }),
      ).rejects.toMatchObject({ code: "FORBIDDEN" });
    }
    expect(mocks.createSignedUploadUrl).not.toHaveBeenCalled();
  });
  test("transaction ownership is checked before presigning", async () => {
    const input = {
      bucket: "vault" as const,
      files: [{ ...file, path: [owner.teamId, "transactions", txId] }],
    };
    await expect(
      createCaller(createTestContext()).createUploadUrls(input),
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(mocks.getTransactionById).toHaveBeenCalledWith(expect.anything(), {
      id: txId,
      teamId: owner.teamId,
    });
    expect(mocks.createSignedUploadUrl).not.toHaveBeenCalled();
    mocks.getTransactionById.mockImplementation(() =>
      Promise.resolve({ id: txId }),
    );
    expect(
      await createCaller(createTestContext()).createUploadUrls(input),
    ).toHaveLength(1);
  });
  test("apps basename is generated by server and public upload completes for receipt owner", async () => {
    mocks.storageHead.mockImplementation(() =>
      Promise.resolve({ size: 123, contentType: "image/png" }),
    );
    const caller = createCaller(createTestContext());
    const [signed] = await caller.createUploadUrls({
      bucket: "apps",
      files: [
        {
          ...file,
          path: ["logos"],
          filename: "client-selected.html",
          contentType: "image/png",
        },
      ],
    });
    expect(signed!.key).toMatch(/^logos\/[A-Za-z0-9_-]{21}\.png$/);
    const result = await caller.completeUploads({
      bucket: "apps",
      files: [{ key: signed!.key, receipt: signed!.receipt }],
    });
    expect(result[0]?.publicUrl).toBe(
      `http://localhost:9000/apps/${signed!.key}`,
    );
    expect(mocks.upsertDocumentForObject).not.toHaveBeenCalled();
  });
  test("declared oversize and nonimage public upload rejected before signing", async () => {
    await expect(
      createCaller(createTestContext()).createUploadUrls({
        bucket: "avatars",
        files: [
          {
            ...file,
            path: [owner.userId],
            contentType: "image/png",
            size: 5 * 1024 * 1024 + 1,
          },
        ],
      }),
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    await expect(
      createCaller(createTestContext()).createUploadUrls({
        bucket: "avatars",
        files: [{ ...file, path: [owner.userId] }],
      }),
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    expect(mocks.createSignedUploadUrl).not.toHaveBeenCalled();
  });
});

describe("tRPC storage completion", () => {
  test("registers verified vault metadata and authenticated owner", async () => {
    const result = await createCaller(createTestContext()).completeUploads(
      await completion(),
    );
    expect(result).toEqual([
      { key: `${owner.teamId}/receipt.pdf`, publicUrl: null },
    ]);
    expect(mocks.upsertDocumentForObject).toHaveBeenCalledWith(
      expect.anything(),
      {
        teamId: owner.teamId,
        key: `${owner.teamId}/receipt.pdf`,
        ownerId: owner.userId,
        size: 123,
        mimetype: "application/pdf",
      },
    );
  });
  test("rejects another user's apps receipt before any object access", async () => {
    await expect(
      createCaller(createTestContext()).completeUploads(
        await completion("logos/file.png", "apps", "other-user"),
      ),
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(mocks.storageHead).not.toHaveBeenCalled();
    expect(mocks.removeStorage).not.toHaveBeenCalled();
  });
  test("rejects forged or different key receipt before accessing ANY batch object", async () => {
    const input = await completion();
    input.files.push({
      key: `${owner.teamId}/different.pdf`,
      receipt: input.files[0]!.receipt,
    });
    await expect(
      createCaller(createTestContext()).completeUploads(input),
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(mocks.storageHead).not.toHaveBeenCalled();
    expect(mocks.removeStorage).not.toHaveBeenCalled();
  });
  test("rechecks transaction ownership even for valid issued receipt", async () => {
    await expect(
      createCaller(createTestContext()).completeUploads(
        await completion(`${owner.teamId}/transactions/${txId}/receipt.pdf`),
      ),
    ).rejects.toMatchObject({ code: "FORBIDDEN" });
    expect(mocks.getTransactionById).toHaveBeenCalledWith(expect.anything(), {
      id: txId,
      teamId: owner.teamId,
    });
    expect(mocks.storageHead).not.toHaveBeenCalled();
  });
  test("missing object fails completion without registering a document", async () => {
    mocks.storageHead.mockImplementation(() => Promise.resolve(null));
    await expect(
      createCaller(createTestContext()).completeUploads(await completion()),
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    expect(mocks.upsertDocumentForObject).not.toHaveBeenCalled();
  });
  test("actual oversize object is deleted, not registered", async () => {
    mocks.storageHead.mockImplementation(() =>
      Promise.resolve({
        size: 101 * 1024 * 1024,
        contentType: "application/pdf",
      }),
    );
    await expect(
      createCaller(createTestContext()).completeUploads(await completion()),
    ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    expect(mocks.removeStorage).toHaveBeenCalledWith("vault", [
      `${owner.teamId}/receipt.pdf`,
    ]);
    expect(mocks.upsertDocumentForObject).not.toHaveBeenCalled();
  });
  test("mismatched size/type and forbidden actual MIME are deleted", async () => {
    for (const object of [
      { size: 124, contentType: "application/pdf" },
      { size: 123, contentType: "text/plain" },
      { size: 123, contentType: "text/html" },
    ]) {
      mocks.storageHead.mockImplementation(() => Promise.resolve(object));
      await expect(
        createCaller(createTestContext()).completeUploads(await completion()),
      ).rejects.toMatchObject({ code: "BAD_REQUEST" });
    }
    expect(mocks.removeStorage).toHaveBeenCalledTimes(3);
    expect(mocks.upsertDocumentForObject).not.toHaveBeenCalled();
  });
});

test("Supabase mode cannot invoke local registration or presigned PUT endpoints", async () => {
  process.env.NEXT_PUBLIC_BACKEND_PROVIDER = "supabase";
  await expect(
    createCaller(createTestContext()).createUploadUrls({
      bucket: "vault",
      files: [file],
    }),
  ).rejects.toMatchObject({ code: "BAD_REQUEST" });
  await expect(
    createCaller(createTestContext()).completeUploads(await completion()),
  ).rejects.toMatchObject({ code: "BAD_REQUEST" });
  expect(mocks.createSignedUploadUrl).not.toHaveBeenCalled();
  expect(mocks.storageHead).not.toHaveBeenCalled();
  expect(mocks.upsertDocumentForObject).not.toHaveBeenCalled();
});
